/** Generated by YAKINDU Statechart Tools code generator. */
package hu.bme.mit.yakindu.analysis.example;

import hu.bme.mit.yakindu.analysis.IStatemachine;
import hu.bme.mit.yakindu.analysis.ITimerCallback;

public interface IExampleStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseBegin();
		
		public void raiseLight();
		
		public void raiseDark();
		
		public long getYellowTime();
		
		public void setYellowTime(long value);
		
		public long getRedTime();
		
		public void setRedTime(long value);
		
	}
	
	public SCInterface getSCInterface();
	
}
